### ISSUE TITLE
Suchfeld setzt sich nicht zurück

### ISSUE THREAD

**Issue by PascalPasitiv** [Sicklas/soundboard#7]
Wenn man was ins Suchfeld eintippt, filtert der die Buttons. Wenn man den Text wieder löscht (über den x Button), setzt er die Filterung aber nicht wieder zurück.

**Comment by Sicklas** [comment]
Quatschticket, was für ein x Button?

**Comment by PascalPasitiv** [comment]
@Sicklas Quatschantwort, dieser x Button!

![2024-07-10 14_23_34-Soundboard](https://github.com/Sicklas/soundboard/assets/125694833/56e88f46-43e3-41a4-a7a1-640087a00b11)

**Comment by Sicklas** [comment]
@PascalPasitiv nutz einfach Firefox oder die Tastatur du Lurch

**Comment by PascalPasitiv** [comment]
@Sicklas Ich dachte das wäre hier ein professionelles Umfeld... Frechheit was dieser Programmierer sich erlaubt! Und jetzt komm Fortnite spielen!
